theme: jekyll-theme-minimal
title: Gustave Kenedi
description: PhD Candidate in Economics at <a href="https://www.sciencespo.fr/department-economics/en.html">Sciences Po</a>, under the supervision of <a href="https://www.gate.cnrs.fr/spip.php?article1024&lang=en/">Pierre-Philippe Combes</a> (University of Lyon and Sciences Po).
contact: "gustavekenedi[at]gmail.com"
show_downloads: false
